version: '3.8'

services:
  node:
    image: rsquared/ees
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/ees
      - ./docker/node/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - node_modules:/var/ees/node_modules
    environment:
      DATABASE_HOST: db
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db
      - rabbitmq
    networks:
      - ees_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
  db:
    image: mysql:5.7
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql_custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/initdb.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/initdb_test.sh:/initdb_test.sh
    networks:
      - ees_network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ees_network

volumes:
  db:
  node_modules:
networks:
  ees_network:
