version: '3.8'

services:
  node:
    image: revpop/ees
    build:
      dockerfile: docker/node/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/ees
      - node_modules:/var/ees/node_modules
    networks:
      - ees_network
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./docker/initdb.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/initdb_test.sh:/initdb_test.sh
    networks:
      - ees_network

volumes:
  db:
  node_modules:
networks:
  ees_network: