mysql -u root -p$MYSQL_ROOT_PASSWORD --execute \
"CREATE DATABASE IF NOT EXISTS $DATABASE_TEST;
GRANT ALL PRIVILEGES ON $DATABASE_TEST.* TO '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_PASSWORD'";

echo "Finished creating test databases"
